const bcrypt = require("bcryptjs");
const Venue = require("./models/Venue");
const Tribe = require("./models/Tribe");
const Member = require("./models/Member");
const Event = require("./models/Event");
const Score = require("./models/Score");
const User = require("./models/User");
const AuditLog = require("./models/AuditLog");

const VENUES = [
  {
    groupName: "Group I",
    venueName: "Venue 1",
    theme: "Creative & Design",
    location: "KRS Seminar Hall",
    motif: "creative",
    participatingClasses: ["AI & DS – A", "CSE – A", "Civil"],
    description: "Aesthetics, innovation, visual harmony, drafting and modern architectural concepts.",
  },
  {
    groupName: "Group II",
    venueName: "Venue 2",
    theme: "Technology & Innovation",
    location: "ECE Seminar Hall",
    motif: "tech",
    participatingClasses: ["Cyber Security", "AI & DS – B", "IT – A"],
    description: "Next-generation computation, algorithmic intelligence, cyber systems and digital transformation.",
  },
  {
    groupName: "Group III",
    venueName: "Venue 3",
    theme: "Space & Cosmic",
    location: "Civil Seminar Hall",
    motif: "space",
    participatingClasses: ["AI & ML", "IT – C", "EEE"],
    description: "Galactic exploration, cosmic navigation, stellar engineering and deep-space science.",
  },
  {
    groupName: "Group IV",
    venueName: "Venue 4",
    theme: "Legends & Mythology",
    location: "MCW Seminar Hall",
    motif: "legend",
    participatingClasses: ["ECE – A", "CSE – B", "MECH"],
    description: "Heroic leadership, classical mythology, valor, resilience and tactical wisdom.",
  },
  {
    groupName: "Group V",
    venueName: "Venue 5",
    theme: "Power & Energy",
    location: "MS Auditorium",
    motif: "energy",
    participatingClasses: ["ECE – B", "CSE – C", "IT – B"],
    description: "Electrical grid innovation, renewable power, atomic dynamism and sustainable energy.",
  },
];

const TRIBE_NAMES = [
  // Group I (Venue 1) - 18 curated teams
  [
    "Pixel Pioneers",
    "Design Dynamo",
    "Imaginex",
    "Aesthetic Architects",
    "Vector Vanguard",
    "Vision Barv I",
    "Blueprint Builders",
    "Prism Prodigies",
    "Creative Catalysts",
    "Form & Function",
    "Vivid Visionaries",
    "Inventory Bubbles",
    "Drafting Dynamos",
    "Spectrum Squad",
    "Origami Ops",
    "Nexus Artisans",
    "Nexora",
    "Kinetic Creations",
  ],
  // Group II (Venue 2) - 18 curated teams
  [
    "Byte Brigade",
    "Cyber Sentinels",
    "Quantum Quarks",
    "Neural Knights",
    "Code Crafters",
    "Silicon Syndicate",
    "Algorithmic Aces",
    "Digital Disruptors",
    "Logic Lords",
    "Cipher Crew",
    "Future Forge",
    "Tech Titans",
    "Matrix Mavens",
    "Binary Blitz",
    "Tech Stars",
    "Kernel Kings",
    "Data Drifters",
    "Apex Automators",
  ],
  // Group III (Venue 3) - 18 curated teams
  [
    "Cosmic Voyagers",
    "Nova Knights",
    "Galaxy Guardians",
    "Stellar Minds",
    "Lunar Legends",
    "Astro Aces",
    "Nebula Ninjas",
    "Orbit Outlaws",
    "Solar Squad",
    "Comet Chasers",
    "Supernova Squad",
    "Celestial Crew",
    "Star Seekers",
    "Cosmic Crusaders",
    "Eclipse Elite",
    "Quasar Questers",
    "Meteor Mavericks",
    "Galactic Giants",
  ],
  // Group IV (Venue 4) - 18 curated teams
  [
    "Phoenix Legion",
    "Titan Force",
    "Algorithmic Assemblers",
    "Nova Squad",
    "Olympian Order",
    "Dragon Riders",
    "Griffin Guild",
    "Slayers",
    "Mythic Mavens",
    "Titanium",
    "Aegis Alliance",
    "Chimera Champions",
    "Immortal Minds",
    "Hydra Harbingers",
    "Samurai Syndicate",
    "Leviathan Lords",
    "Colossus Corps",
    "Centaur Cohort",
  ],
  // Group V (Venue 5) - 19 curated teams
  [
    "Voltric Sparks",
    "Wonderwatt",
    "Ignite X",
    "Volt Coders",
    "Watt A Team",
    "Energon",
    "Energy Titans",
    "Power Nautical",
    "Solar Panel",
    "Destructive mc²",
    "Luminous",
    "Circuit Breakers",
    "Kinetic Knights",
    "Electra",
    "Volt Warriors",
    "Power Dynasty",
    "Power Rangers",
    "Enerzinc Pulse",
    "Voltelites",
  ],
];

const FIRST_NAMES = [
  "Aarav", "Diya", "Karthik", "Meera", "Rahul", "Sneha", "Vikram", "Ananya", "Hari", "Priya",
  "Siddharth", "Pooja", "Gautam", "Swathi", "Rohan", "Tanvi", "Aditya", "Keerthi", "Naveen", "Divya",
  "Varun", "Rhea", "Arjun", "Lakshmi", "Madhav", "Kavya", "Vishnu", "Shreya", "Surya", "Harini"
];

const LAST_NAMES = [
  "Iyer", "Krishnan", "Ramesh", "Nair", "Sharma", "Reddy", "Menon", "Das", "Pillai", "Kumar",
  "Venkatesh", "Balaji", "Subramanian", "Natarajan", "Sundaram", "Choudhury", "Patel", "Murugan", "Srinivasan", "Chandran"
];

const EVENTS = [
  { eventName: "Tear Down Lab", description: "Hands-on disassembly, component analysis and systems thinking.", maximumScore: 100 },
  { eventName: "Poster Presentation", description: "Visual storytelling and theme concept articulation.", maximumScore: 100 },
  { eventName: "Problem Hunt", description: "Problem-solving challenge and critical thinking assessment.", maximumScore: 100 },
];


async function seedDatabase({ force = false } = {}) {
  const existingCount = await Tribe.countDocuments();
  if (existingCount > 0 && !force) {
    return { seeded: false, tribes: existingCount };
  }

  // Clear existing collections if forcing or re-seeding
  await Promise.all([
    Venue.deleteMany({}),
    Tribe.deleteMany({}),
    Member.deleteMany({}),
    Event.deleteMany({}),
    Score.deleteMany({}),
    User.deleteMany({}),
    AuditLog.deleteMany({}),
  ]);

  const venues = await Venue.insertMany(VENUES);
  const events = await Event.insertMany(EVENTS);

  const tribes = [];
  let code = 1;
  venues.forEach((venue, venueIndex) => {
    TRIBE_NAMES[venueIndex].forEach((name) => {
      tribes.push({
        tribeCode: `SIP-${String(code).padStart(3, "0")}`,
        tribeName: name,
        groupName: venue.groupName,
        venueId: venue._id,
        theme: venue.theme,
        status: "active",
      });
      code += 1;
    });
  });
  const createdTribes = await Tribe.insertMany(tribes);

  const GROUP1_VERIFIED_MEMBERS = {
    "Vector Vanguard": [
      { name: "Harish. M", department: "AI & DS", classSection: "AIDS" },
      { name: "Gowtham. N", department: "AI & DS", classSection: "AIDS" },
      { name: "Dharanish. M", department: "AI & DS", classSection: "AIDS" },
      { name: "Mukesh Krishna", department: "AI & DS", classSection: "AIDS" },
      { name: "Tamilarasu. J", department: "Civil", classSection: "Civil" },
      { name: "Abiraj", department: "Civil", classSection: "Civil" },
      { name: "Manikandan", department: "Civil", classSection: "Civil" },
      { name: "Nithish", department: "Civil", classSection: "Civil" },
      { name: "Harish. S", department: "AI & DS", classSection: "AI/DS" },
      { name: "M. Mohamed Kasim", department: "AI & DS", classSection: "AI/DS" },
    ],
    "Vivid Visionaries": [
      { name: "Asgar Mehdi", department: "AI & DS", classSection: "AI/DS" },
      { name: "Moulish. E", department: "AI & DS", classSection: "AI/DS" },
      { name: "Madhan Kumar", department: "AI & DS", classSection: "AI/DS" },
      { name: "Kaniskan", department: "AI & DS", classSection: "AI/DS" },
      { name: "Kamalesh", department: "CSE", classSection: "CSE" },
      { name: "Hariharan. J", department: "CSE", classSection: "CSE" },
      { name: "Kamal", department: "CSE", classSection: "CSE" },
      { name: "Hari Kumar", department: "CSE", classSection: "CSE" },
      { name: "Rakesh", department: "Civil", classSection: "Civil" },
      { name: "Vishal Paul. M", department: "Civil", classSection: "Civil" },
    ],
    "Origami Ops": [
      { name: "Anbu Chezhiyan. S", department: "Civil", classSection: "Civil" },
      { name: "Anbu Selvan. S", department: "Civil", classSection: "Civil" },
      { name: "Sam. M", department: "Civil", classSection: "Civil" },
      { name: "Bharath. S", department: "CSE", classSection: "CSE" },
      { name: "Paraniv. S", department: "Civil", classSection: "Civil" },
      { name: "Jithendra Kumar. R", department: "CSE", classSection: "CSE" },
      { name: "Vimal Raja. V", department: "Civil", classSection: "Civil" },
      { name: "Harshad. R", department: "CSE", classSection: "CSE" },
      { name: "Dharanidharan. V", department: "AI & DS", classSection: "AIDS" },
      { name: "Jeevan. D", department: "AI & DS", classSection: "AIDS" },
      { name: "Imtiha. K", department: "CSE", classSection: "CSE" },
    ],
    "Kinetic Creations": [
      { name: "Deepesh. N", department: "Creative & Design", classSection: "Group I" },
      { name: "Kamaleshwar. G", department: "Creative & Design", classSection: "Group I" },
      { name: "Harish Snehan", department: "Creative & Design", classSection: "Group I" },
      { name: "Jeeva Prakash", department: "Creative & Design", classSection: "Group I" },
      { name: "Balamukesh. V", department: "Creative & Design", classSection: "Group I" },
      { name: "Harish Kumar", department: "Creative & Design", classSection: "Group I" },
      { name: "Deepan Saonathy", department: "Creative & Design", classSection: "Group I" },
      { name: "Gowtham", department: "Creative & Design", classSection: "Group I" },
      { name: "Dinesh", department: "Creative & Design", classSection: "Group I" },
      { name: "Harish Kumar", department: "Creative & Design", classSection: "Group I" },
    ],
    "Spectrum Squad": [
      { name: "Abhinav. N", department: "Creative & Design", classSection: "Group I" },
      { name: "Shakid. S", department: "Creative & Design", classSection: "Group I" },
      { name: "Dinesh Karthikeyan. K", department: "Creative & Design", classSection: "Group I" },
      { name: "Harshavardhan. M", department: "Creative & Design", classSection: "Group I" },
      { name: "Dhanush. T", department: "Creative & Design", classSection: "Group I" },
    ],
    "Vision Barv I": [
      { name: "Aaqil Hafeez. N", department: "CSE", classSection: "B.E CSE" },
      { name: "Janagan R.S", department: "CSE", classSection: "B.E CSE" },
      { name: "Gokul. G", department: "CSE", classSection: "B.E CSE" },
      { name: "Ashwin Krishna. V", department: "CSE", classSection: "B.E CSE" },
      { name: "Adnan A.R", department: "AI & DS", classSection: "AIDS" },
      { name: "Gokulnath", department: "AI & DS", classSection: "AIDS" },
      { name: "Abdullah. K", department: "AI & DS", classSection: "AIDS" },
      { name: "A. Hamed Faarish. M", department: "AI & DS", classSection: "AIDS" },
      { name: "Suriya Prakash. S", department: "Civil", classSection: "Civil" },
      { name: "Santhosh. K", department: "Civil", classSection: "Civil" },
    ],
    "Nexus Artisans": [
      { name: "Yugesh", department: "Civil", classSection: "Civil" },
      { name: "Aufrash", department: "Civil", classSection: "Civil" },
      { name: "Dharani", department: "Civil", classSection: "Civil" },
      { name: "Sanjeevan", department: "Civil", classSection: "Civil" },
      { name: "Grauthan", department: "CSE", classSection: "CSE" },
      { name: "Bhuvaneshwaran", department: "CSE", classSection: "CSE" },
      { name: "E. Byelijah", department: "CSE", classSection: "CSE" },
      { name: "Kalvin Christopher", department: "AI & DS", classSection: "AI,DS" },
    ],
    "Imaginex": [
      { name: "Sanjay (Leader)", department: "Civil", classSection: "Civil" },
      { name: "Elantheeran", department: "CSE", classSection: "CSE" },
      { name: "Gokul", department: "CSE", classSection: "CSE" },
      { name: "Peter", department: "CSE", classSection: "CSE" },
      { name: "Sasi", department: "Civil", classSection: "Civil" },
      { name: "Rohit", department: "Civil", classSection: "Civil" },
      { name: "Sanjay Dharshan", department: "Civil", classSection: "Civil" },
      { name: "Lalith", department: "AI & DS", classSection: "AI/DS" },
      { name: "Imthiyaz", department: "AI & DS", classSection: "AI/DS" },
      { name: "Deepash", department: "CSE", classSection: "CSE" },
    ],
    "Prism Prodigies": [
      { name: "Dharshini. S. G", department: "CSE", classSection: "CSE" },
      { name: "Elampirai Sakthi. V", department: "Civil", classSection: "Civil" },
      { name: "Apernaa Gayathri. A", department: "CSE", classSection: "CSE" },
      { name: "Shangavi. S", department: "Civil", classSection: "Civil" },
      { name: "Roobahasini. M", department: "Civil", classSection: "Civil" },
      { name: "Kirthika S", department: "AI & DS", classSection: "AI & DS" },
      { name: "Divya. V", department: "AI & DS", classSection: "AI & DS" },
      { name: "Magaleksmi. V", department: "Civil", classSection: "Civil" },
      { name: "Dhanushya. K", department: "AI & DS", classSection: "AI & DS" },
      { name: "Yashwantika. S", department: "Civil", classSection: "Civil" },
    ],
    "Drafting Dynamos": [
      { name: "Harini. H", department: "CSE", classSection: "CSE A" },
      { name: "Monika. S", department: "AI & DS", classSection: "AIDS A" },
      { name: "Danyasree. N", department: "AI & DS", classSection: "AIDS A" },
      { name: "Akshaya. A", department: "AI & DS", classSection: "AIDS A" },
      { name: "Dhanashree. G", department: "CSE", classSection: "CSE A" },
      { name: "Hemaashree. V", department: "AI & DS", classSection: "AIDS A" },
      { name: "Ambreen Haniyah KM", department: "CSE", classSection: "CSE A" },
      { name: "Abinaya. S", department: "CSE", classSection: "CSE A" },
      { name: "Dhujasri. J", department: "AI & DS", classSection: "AIDS A" },
      { name: "Bavana. P", department: "AI & DS", classSection: "AIDS A" },
    ],
    "Nexora": [
      { name: "Darshinika. P", department: "CSE", classSection: "CSE" },
      { name: "Hemavathy. R", department: "CSE", classSection: "CSE" },
      { name: "Aarthika. B.M", department: "CSE", classSection: "CSE" },
      { name: "Gayathri. M", department: "CSE", classSection: "CSE" },
      { name: "Anugraha Pradaa. A.P", department: "CSE", classSection: "CSE" },
      { name: "Renuka Devi. K", department: "Civil", classSection: "Civil" },
      { name: "Monika. T", department: "AI & DS", classSection: "AIDS" },
      { name: "Divya. K", department: "Civil", classSection: "Civil" },
      { name: "Lajjana. R", department: "AI & DS", classSection: "AIDS" },
      { name: "Anushri. E", department: "Civil", classSection: "Civil" },
    ],
    "Inventory Bubbles": [
      { name: "Dhishya Nethra. R", department: "CSE", classSection: "CSE A" },
      { name: "Aafiya. K", department: "AI & DS", classSection: "AIDS A" },
      { name: "Charishma Golthi", department: "CSE", classSection: "CSE A" },
      { name: "Aysha Rifnath. A", department: "AI & DS", classSection: "AIDS A" },
      { name: "L. Hajika", department: "CSE", classSection: "CSE A" },
      { name: "Methula. P", department: "AI & DS", classSection: "AIDS A" },
      { name: "Jayalakshmi. B", department: "AI & DS", classSection: "AIDS A" },
      { name: "Hashini. M.S", department: "CSE", classSection: "CSE A" },
      { name: "Yaja Priya. N", department: "CSE", classSection: "CSE A" },
      { name: "Bavadharani. K", department: "CSE", classSection: "CSE A" },
    ],
    "Design Dynamo": [
      { name: "Afrah", department: "Creative & Design", classSection: "Group I" },
      { name: "Janani K", department: "CSE", classSection: "CSE" },
      { name: "Mubeena", department: "AI & DS", classSection: "AIDS(A)" },
      { name: "Blessy", department: "CSE / AI & DS", classSection: "CSE/AIDS (A)" },
      { name: "Dhana Shri", department: "CSE", classSection: "CSE" },
      { name: "Rochelle", department: "CSE", classSection: "CSE" },
      { name: "Divya Dharshini", department: "AI & DS", classSection: "AIDS" },
      { name: "Aishwarya", department: "AI & DS", classSection: "AIDS" },
      { name: "Athya", department: "CSE", classSection: "CSE" },
      { name: "Janani", department: "CSE", classSection: "CSE" },
    ],
    "Blueprint Builders": [
      { name: "Aradhana. P", department: "CSE", classSection: "CSE-A" },
      { name: "Asmitha. P", department: "AI & DS", classSection: "AI-DS-A" },
      { name: "Menaka N", department: "AI & DS", classSection: "AI-DS-A" },
      { name: "Logapriya D", department: "AI & DS", classSection: "AI-DS-A" },
      { name: "Harini. M.R", department: "CSE", classSection: "CSE-A" },
      { name: "Harini. M", department: "CSE", classSection: "CSE-A" },
      { name: "Lavanya", department: "AI & DS", classSection: "AI-DS-A" },
      { name: "Kaviya", department: "AI & DS", classSection: "AI-DS-A" },
      { name: "Hasifa Tabassum. N", department: "AI & DS", classSection: "AI-DS-A" },
      { name: "Harlean Ricky K", department: "AI & DS", classSection: "AI-DS-A" },
    ],
    "Aesthetic Architects": [
      { name: "V. Mathumitha", department: "AI & DS", classSection: "AIDS" },
      { name: "M. Jeffy", department: "AI & DS", classSection: "AIDS" },
      { name: "B. Divya Dharshini", department: "AI & DS", classSection: "AIDS" },
      { name: "P. Darsha", department: "CSE", classSection: "CSE" },
      { name: "J. Divya Darshini", department: "CSE", classSection: "CSE" },
      { name: "Dharshini. S", department: "CSE", classSection: "CSE 'A'" },
      { name: "J. Jessy Rebekah", department: "CSE", classSection: "CSE-A" },
      { name: "P. Keerthi", department: "Creative & Design", classSection: "Group I" },
      { name: "Dipsikha. R", department: "AI & DS", classSection: "AIDS" },
      { name: "Meghasree. S", department: "AI & DS", classSection: "AIDS" },
    ],
    "Pixel Pioneers": [
      { name: "Aadharshana", department: "Civil", classSection: "Civil" },
      { name: "Deva Karini", department: "Civil", classSection: "CIVIL" },
      { name: "Sivadarshana", department: "Civil", classSection: "CIVIL" },
      { name: "Vaishali", department: "Civil", classSection: "CIVIL" },
      { name: "Priyanka", department: "Civil", classSection: "CIVIL" },
      { name: "Manasa", department: "AI & DS", classSection: "AIDS" },
      { name: "Angel", department: "AI & DS", classSection: "AIDS" },
      { name: "Lavanya", department: "AI & DS", classSection: "AIDS" },
      { name: "Gowri", department: "Creative & Design", classSection: "Group I" },
      { name: "Nisha", department: "Creative & Design", classSection: "Group I" },
    ],
  };

  const GROUP2_VERIFIED_MEMBERS = {
    "Byte Brigade": [
      { name: "Syed Suhaib", department: "AI & DS", classSection: "AI/DS (B)" },
      { name: "Nethran", department: "AI & DS", classSection: "AI/DS (B)" },
      { name: "Ramki", department: "AI & DS", classSection: "AI/DS (B)" },
      { name: "Vinoth", department: "AI & DS", classSection: "AI/DS (B)" },
      { name: "Deva Chandra", department: "IT", classSection: "IT" },
      { name: "Irsae", department: "IT", classSection: "IT (A)" },
      { name: "Anish", department: "IT", classSection: "IT (A)" },
      { name: "M. Riyaz Ahamed", department: "Cyber Security", classSection: "CSE (CS)" },
      { name: "Rathish", department: "Cyber Security", classSection: "CSE (CS)" },
      { name: "Dhakshan", department: "Cyber Security", classSection: "CSE (CS)" },
    ],
    "Cyber Sentinels": [
      { name: "D Vishal", department: "Cyber Security", classSection: "Cyber" },
      { name: "Lakshath", department: "Cyber Security", classSection: "Cyber" },
      { name: "Nithish", department: "Cyber Security", classSection: "Cyber" },
      { name: "Yeshwinth", department: "Cyber Security", classSection: "Cyber" },
      { name: "Monish", department: "Cyber Security", classSection: "Cyber" },
      { name: "Giridhar", department: "Cyber Security", classSection: "CSE (CS)" },
      { name: "Boopesh L", department: "Cyber Security", classSection: "CSE (CS)" },
      { name: "Dakshnan", department: "Cyber Security", classSection: "CSE (CS)" },
    ],
    "Quantum Quarks": [
      { name: "Yuvasree K", department: "AI & DS", classSection: "AIDS" },
      { name: "Yokapriya T", department: "AI & DS", classSection: "AIDS" },
      { name: "Shahana Nisha N", department: "AI & DS", classSection: "AIDS" },
      { name: "Pavithra E", department: "AI & DS", classSection: "AIDS" },
      { name: "Ramya S", department: "AI & DS", classSection: "AIDS" },
      { name: "Shanthini M", department: "AI & DS", classSection: "AIDS" },
      { name: "Rahmika R R", department: "AI & DS", classSection: "AIDS" },
      { name: "Ramya R", department: "AI & DS", classSection: "AIDS" },
      { name: "Saya M A R", department: "AI & DS", classSection: "AIDS" },
      { name: "Adeeba Kavex A", department: "AI & DS", classSection: "AIDS" },
    ],
    "Neural Knights": [
      { name: "Sanjai Kumar R", department: "AI & DS", classSection: "AI/DS (B)" },
      { name: "Sanjay T S", department: "AI & DS", classSection: "AI/DS (B)" },
      { name: "Prithish Kumar C", department: "AI & DS", classSection: "AI/DS (B)" },
      { name: "Tamil", department: "AI & DS", classSection: "AI/DS (B)" },
      { name: "Sai Ram", department: "AI & DS", classSection: "AI/DS (B)" },
      { name: "Rohith", department: "AI & DS", classSection: "AI/DS (B)" },
      { name: "Sakthi", department: "AI & DS", classSection: "AI/DS (B)" },
      { name: "Sathiya Moorthy", department: "AI & DS", classSection: "AI/DS (B)" },
      { name: "Vinoth", department: "AI & DS", classSection: "AI/DS (B)" },
      { name: "Ramki", department: "AI & DS", classSection: "AI/DS (B)" },
      { name: "Syed Mohammed Reza", department: "AI & DS", classSection: "AI/DS (B)" },
    ],
    "Silicon Syndicate": [
      { name: "Sivani P", department: "AI & DS", classSection: "AIDS" },
      { name: "L Yoha Lakshmi", department: "AI & DS", classSection: "AIDS" },
      { name: "Sai Santhiniya S D", department: "AI & DS", classSection: "AIDS" },
      { name: "Vedhasree K", department: "AI & DS", classSection: "AIDS" },
      { name: "Poorna B M", department: "Cyber Security", classSection: "CSE (CS)" },
      { name: "Madhu Sri E", department: "Cyber Security", classSection: "CSE (CS)" },
      { name: "Gopika V", department: "Cyber Security", classSection: "CSE (CS)" },
      { name: "K Kavitha", department: "Cyber Security", classSection: "CSE (CS)" },
      { name: "Kumudhini Shri S", department: "Cyber Security", classSection: "CSE (CS)" },
      { name: "Nivedha Sri", department: "Cyber Security", classSection: "CSE (CS)" },
    ],
    "Algorithmic Aces": [
      { name: "Anu Harini RHA", department: "IT", classSection: "IT-A" },
      { name: "Aishwarya", department: "IT", classSection: "IT-A" },
      { name: "Harini V", department: "IT", classSection: "IT-A" },
      { name: "Dharani Sri K", department: "IT", classSection: "IT-A" },
      { name: "Ankita Tiwari", department: "IT", classSection: "IT-A" },
      { name: "Deepika N", department: "IT", classSection: "IT-A" },
      { name: "Elkia K", department: "IT", classSection: "IT-A" },
      { name: "Ishwarya K", department: "IT", classSection: "IT-A" },
      { name: "Blessy Jasamin A", department: "IT", classSection: "IT-A" },
      { name: "Aathmika M", department: "IT", classSection: "IT-A" },
    ],
    "Logic Lords": [
      { name: "Samsun Fasiya", department: "Cyber Security", classSection: "Cyber Security" },
      { name: "Sangrita", department: "Cyber Security", classSection: "Cyber Security" },
      { name: "Niranjana", department: "Cyber Security", classSection: "Cyber Security" },
      { name: "Geetha", department: "Cyber Security", classSection: "Cyber Security" },
      { name: "Rashmi", department: "Cyber Security", classSection: "Cyber Security" },
      { name: "Janani", department: "Cyber Security", classSection: "Cyber Security" },
      { name: "Daphin", department: "Cyber Security", classSection: "Cyber Security" },
      { name: "Sarah", department: "Cyber Security", classSection: "Cyber Security" },
      { name: "Atheefa", department: "Cyber Security", classSection: "Cyber Security" },
    ],
    "Cipher Crew": [
      { name: "Harshini", department: "IT", classSection: "IT" },
      { name: "Madhura", department: "IT", classSection: "IT" },
      { name: "Puranjani", department: "IT", classSection: "IT" },
      { name: "Yasmeen", department: "AI & DS", classSection: "AI/DS (B)" },
      { name: "Sahla Rasina", department: "AI & DS", classSection: "AI/DS (B)" },
      { name: "Harini", department: "IT", classSection: "IT" },
      { name: "Agalya", department: "IT", classSection: "IT" },
      { name: "Kaviya S", department: "Cyber Security", classSection: "CSE (CS)" },
      { name: "Abhisa A", department: "Cyber Security", classSection: "CSE (CS)" },
      { name: "Shimaranjani", department: "AI & DS", classSection: "AI/DS" },
    ],
    "Future Forge": [
      { name: "Asmitha", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Ananya", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Deepika", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Hazana", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Akshaya", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Harshini", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Dhilshath", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Abinaya", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Divyabharathi", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Jenniya", department: "Technology & Innovation", classSection: "Group II" },
    ],
    "Tech Titans": [
      { name: "Yogith P", department: "IT", classSection: "IT" },
      { name: "Sanjay B", department: "IT", classSection: "IT" },
      { name: "Puranthar AB", department: "IT", classSection: "IT" },
      { name: "Nisanth S", department: "IT", classSection: "IT" },
      { name: "Vijaya Ragav E", department: "IT", classSection: "IT" },
      { name: "Abinesh M", department: "IT", classSection: "IT" },
      { name: "Anish Antony R", department: "IT", classSection: "IT" },
      { name: "Balapriyan T", department: "IT", classSection: "IT" },
      { name: "Bharanidharan M", department: "IT", classSection: "IT" },
      { name: "Pavan Raj N", department: "IT", classSection: "IT" },
    ],
    "Matrix Mavens": [
      { name: "Muskan M", department: "Cyber Security", classSection: "CYS" },
      { name: "Kiranmayi B", department: "Cyber Security", classSection: "CYS" },
      { name: "Tuhina S", department: "Cyber Security", classSection: "CYS" },
      { name: "Gayathri V", department: "Cyber Security", classSection: "CYS" },
      { name: "Anusha A", department: "IT", classSection: "IT" },
      { name: "Andal Dharshini", department: "IT", classSection: "IT" },
      { name: "Sri Vishnu Priya", department: "AI & DS", classSection: "AI/DS" },
      { name: "Ruba Zainab N", department: "AI & DS", classSection: "AI/DS" },
      { name: "Rakshithak B", department: "AI & DS", classSection: "AI/DS" },
      { name: "Vishnu Priya A", department: "AI & DS", classSection: "AI/DS" },
    ],
    "Binary Blitz": [
      { name: "Mahashreeya M", department: "Cyber Security", classSection: "Cyber" },
      { name: "Mamtha M", department: "AI & DS", classSection: "AIDS-B" },
      { name: "Sandhiya S", department: "IT", classSection: "IT-A" },
      { name: "Keerthilakshmi V", department: "AI & DS", classSection: "AIDS-B" },
      { name: "Akshaya S V", department: "IT", classSection: "IT-A" },
      { name: "Subha Lakshmi", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Nafia Shiroze", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Vigacini", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Priyanka", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Sri Hamsini Poraturi", department: "Technology & Innovation", classSection: "Group II" },
    ],
    "Tech Stars": [
      { name: "Saghithya M S", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Rachel", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Riya Shain", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Yogarathna", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Praisy Gifta", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Thirisha", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Shamini", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Sakthi Janani", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Prithika", department: "Technology & Innovation", classSection: "Group II" },
      { name: "Daphine", department: "Technology & Innovation", classSection: "Group II" },
    ],
    "Data Drifters": [
      { name: "Sudharsan", department: "Cyber Security", classSection: "CSE (CY)" },
      { name: "Lokesh Kumaran M", department: "Cyber Security", classSection: "Cyber Security" },
      { name: "Kishore K", department: "Cyber Security", classSection: "CSE (CY)" },
      { name: "Manish", department: "Cyber Security", classSection: "CSE (CY)" },
      { name: "Shankkarthick", department: "Cyber Security", classSection: "CSE (CY)" },
      { name: "Sricharan", department: "Cyber Security", classSection: "CSE (CY)" },
      { name: "Ragul Doni A", department: "Cyber Security", classSection: "CSE (CY)" },
      { name: "Abu Khan", department: "Cyber Security", classSection: "CSE (CY)" },
      { name: "Keerthanesh", department: "Cyber Security", classSection: "CSE (CY)" },
      { name: "Arun Kumar", department: "Cyber Security", classSection: "CSE (CY)" },
    ],
    "Apex Automators": [
      { name: "Jaishnu F", department: "IT", classSection: "IT" },
      { name: "Buvaneswar K", department: "IT", classSection: "IT" },
      { name: "Akash V", department: "IT", classSection: "IT" },
      { name: "Aswinth A", department: "IT", classSection: "IT" },
      { name: "Hemanth Raj T", department: "IT", classSection: "IT" },
      { name: "Akash N A", department: "IT", classSection: "IT" },
      { name: "Guru Prosath M", department: "IT", classSection: "IT" },
      { name: "Anirudh", department: "IT", classSection: "IT" },
      { name: "Barath Kumar K", department: "IT", classSection: "IT" },
      { name: "Gowtham K", department: "IT", classSection: "IT" },
    ],
  };

  const GROUP3_VERIFIED_MEMBERS = {
    "Cosmic Voyagers": [
      { name: "MOHAMMED WAHID A", department: "AI & ML", classSection: "AIML" },
      { name: "NIVAAS M", department: "AI & ML", classSection: "AIML" },
      { name: "NITHESH K", department: "AI & ML", classSection: "AIML" },
      { name: "SANJAY R", department: "IT", classSection: "IT C" },
      { name: "RAGHUL P", department: "IT", classSection: "IT C" },
      { name: "SIVANI B", department: "IT", classSection: "IT C" },
      { name: "BHARAT KRISHNAN D", department: "EEE", classSection: "EEE" },
      { name: "KAARTHIKEYAN S B", department: "EEE", classSection: "EEE" },
      { name: "ARAVIND S", department: "EEE", classSection: "EEE" },
      { name: "SAKTHI SUBBURAYAN S", department: "EEE", classSection: "EEE" },
    ],
    "Nova Knights": [
      { name: "LINGESH D", department: "AI & ML", classSection: "AIML" },
      { name: "SHAREEN SHAM V", department: "AI & ML", classSection: "AIML" },
      { name: "GOKUL S", department: "AI & ML", classSection: "AIML" },
      { name: "YOGESH R", department: "IT", classSection: "IT C" },
      { name: "SANTHOSH A", department: "IT", classSection: "IT C" },
      { name: "SARATH KUMAR S", department: "IT", classSection: "IT C" },
      { name: "ATHREYA PRABHU K", department: "EEE", classSection: "EEE" },
      { name: "AJMAL A", department: "EEE", classSection: "EEE" },
      { name: "VIJAYA GANAPATHY M", department: "EEE", classSection: "EEE" },
      { name: "YUKESH R", department: "EEE", classSection: "EEE" },
    ],
    "Galaxy Guardians": [
      { name: "SUDHAN G", department: "AI & ML", classSection: "AIML" },
      { name: "KATHIREZHILAN T", department: "AI & ML", classSection: "AIML" },
      { name: "NITHIESH K", department: "AI & ML", classSection: "AIML" },
      { name: "VISHWATH KATHIR M", department: "IT", classSection: "IT C" },
      { name: "THIRUMARAN A P M", department: "IT", classSection: "IT C" },
      { name: "SARVESH K", department: "IT", classSection: "IT C" },
      { name: "SRIRAM K S", department: "EEE", classSection: "EEE" },
      { name: "LOKESH KUMAR I", department: "EEE", classSection: "EEE" },
      { name: "SHRIRAM MURALI IYER", department: "EEE", classSection: "EEE" },
      { name: "SUNIL KUMAR J", department: "EEE", classSection: "EEE" },
    ],
    "Stellar Minds": [
      { name: "ABISHEK C", department: "AI & ML", classSection: "AIML" },
      { name: "VISHNU PRIYA K", department: "AI & ML", classSection: "AIML" },
      { name: "MADHESH P", department: "AI & ML", classSection: "AIML" },
      { name: "SUJAN J", department: "IT", classSection: "IT C" },
      { name: "SRIRAAG S", department: "IT", classSection: "IT C" },
      { name: "RAVI SHANKER P", department: "IT", classSection: "IT C" },
      { name: "TARUN S", department: "EEE", classSection: "EEE" },
      { name: "YUVANSANKAR K", department: "EEE", classSection: "EEE" },
      { name: "SANJEEVI KUMAR P", department: "EEE", classSection: "EEE" },
      { name: "RAHUL N", department: "EEE", classSection: "EEE" },
    ],
    "Lunar Legends": [
      { name: "DINESH KUMAR M", department: "AI & ML", classSection: "AIML" },
      { name: "NANDHA KUMAR S", department: "AI & ML", classSection: "AIML" },
      { name: "NIKASH S", department: "AI & ML", classSection: "AIML" },
      { name: "SIVA SAKTHI T", department: "IT", classSection: "IT C" },
      { name: "UDIT ROSHAN A", department: "IT", classSection: "IT C" },
      { name: "THARUN K", department: "IT", classSection: "IT C" },
      { name: "JOSHUA SAMPATH S", department: "EEE", classSection: "EEE" },
      { name: "NAVEEN KUMAR S", department: "EEE", classSection: "EEE" },
      { name: "SABESWARAN K", department: "EEE", classSection: "EEE" },
      { name: "GIRI JOYESAN S", department: "EEE", classSection: "EEE" },
    ],
    "Astro Aces": [
      { name: "NAVEEN M N", department: "AI & ML", classSection: "AIML" },
      { name: "GOPINATH J", department: "AI & ML", classSection: "AIML" },
      { name: "MITHRAN KUMAR V", department: "AI & ML", classSection: "AIML" },
      { name: "SIVA HARI S", department: "IT", classSection: "IT C" },
      { name: "SRIVENGADA KRISHNAN S", department: "IT", classSection: "IT C" },
      { name: "VETRI S", department: "IT", classSection: "IT C" },
      { name: "HARIHARAN B", department: "EEE", classSection: "EEE" },
      { name: "CHANDRU S", department: "EEE", classSection: "EEE" },
      { name: "VELMURUGAN R", department: "EEE", classSection: "EEE" },
      { name: "KARTHICK V", department: "EEE", classSection: "EEE" },
    ],
    "Nebula Ninjas": [
      { name: "MUGUNTHAN M R", department: "AI & ML", classSection: "AIML" },
      { name: "YUVAN SHANKAR C P", department: "AI & ML", classSection: "AIML" },
      { name: "ASHWANTH A", department: "AI & ML", classSection: "AIML" },
      { name: "Yathish R", department: "IT", classSection: "IT C" },
      { name: "SHANMUGAVEL V", department: "IT", classSection: "IT C" },
      { name: "VETRIVEL L", department: "IT", classSection: "IT C" },
      { name: "SANJAY G", department: "EEE", classSection: "EEE" },
      { name: "NISHANTH RAM S", department: "EEE", classSection: "EEE" },
      { name: "SRI VEKKA BALA SUBRAMANI S", department: "EEE", classSection: "EEE" },
      { name: "MOHAMED MURSHITH M", department: "EEE", classSection: "EEE" },
    ],
    "Orbit Outlaws": [
      { name: "PRAVEEN D", department: "AI & ML", classSection: "AIML" },
      { name: "BALA S", department: "AI & ML", classSection: "AIML" },
      { name: "LALITH KUMAR J", department: "AI & ML", classSection: "AIML" },
      { name: "THARAN SANJAY S", department: "IT", classSection: "IT C" },
      { name: "VEDHANTH V", department: "IT", classSection: "IT C" },
      { name: "SHAWN WILLIAMS MC CONNELL", department: "IT", classSection: "IT C" },
      { name: "VENKAT SRIRAM S", department: "EEE", classSection: "EEE" },
      { name: "NITHISH K", department: "EEE", classSection: "EEE" },
      { name: "POOVARASAN M", department: "EEE", classSection: "EEE" },
      { name: "MURUGAN S", department: "EEE", classSection: "EEE" },
    ],
    "Solar Squad": [
      { name: "PRADHISHA D", department: "AI & ML", classSection: "AIML" },
      { name: "PAVITHRA T", department: "AI & ML", classSection: "AIML" },
      { name: "JANANI A K", department: "AI & ML", classSection: "AIML" },
      { name: "KANISHKA N", department: "AI & ML", classSection: "AIML" },
      { name: "SRINITHI S", department: "AI & ML", classSection: "AIML" },
      { name: "SURUTHIKA V", department: "IT", classSection: "IT C" },
      { name: "TANUSHRI J", department: "IT", classSection: "IT C" },
      { name: "SHRUTHI S", department: "IT", classSection: "IT C" },
      { name: "ANANTIKA S", department: "EEE", classSection: "EEE" },
      { name: "GOPIKA S", department: "EEE", classSection: "EEE" },
    ],
    "Comet Chasers": [
      { name: "BHAVATHARANI K", department: "AI & ML", classSection: "AIML" },
      { name: "VASUNDHARA DEVI TIRUMANI", department: "AI & ML", classSection: "AIML" },
      { name: "SUPRIYA S", department: "AI & ML", classSection: "AIML" },
      { name: "MADHUNISHA V", department: "AI & ML", classSection: "AIML" },
      { name: "BHAVANA K", department: "AI & ML", classSection: "AIML" },
      { name: "SHIVANI R", department: "IT", classSection: "IT C" },
      { name: "YUVASHREE K", department: "IT", classSection: "IT C" },
      { name: "VAIBHAVALAKSHMI A", department: "IT", classSection: "IT C" },
      { name: "NISHANTHINI P", department: "EEE", classSection: "EEE" },
      { name: "ILAKIYA SHREE M", department: "EEE", classSection: "EEE" },
    ],
    "Supernova Squad": [
      { name: "SAMIKSHA PARAMESHWARI G", department: "AI & ML", classSection: "AIML" },
      { name: "THANU SHREE", department: "AI & ML", classSection: "AIML" },
      { name: "DHANUSHIYA K", department: "AI & ML", classSection: "AIML" },
      { name: "PAVITHRA D", department: "AI & ML", classSection: "AIML" },
      { name: "SUDARSHANA SREE K V", department: "IT", classSection: "IT C" },
      { name: "YASMEEN M", department: "IT", classSection: "IT C" },
      { name: "TRINITA S", department: "IT", classSection: "IT C" },
      { name: "RAKSHAMBIKA C B", department: "IT", classSection: "IT C" },
      { name: "THITHIKSHA J", department: "EEE", classSection: "EEE" },
      { name: "ARCHANA A", department: "EEE", classSection: "EEE" },
    ],
    "Celestial Crew": [
      { name: "SAGANA SRI S", department: "AI & ML", classSection: "AIML" },
      { name: "AHARSHANA M", department: "AI & ML", classSection: "AIML" },
      { name: "DEVIKA D", department: "AI & ML", classSection: "AIML" },
      { name: "HANIYA LIYA S A", department: "AI & ML", classSection: "AIML" },
      { name: "Rivetha G", department: "IT", classSection: "IT C" },
      { name: "RAJESHWARI P", department: "IT", classSection: "IT C" },
      { name: "RIJITHA R", department: "IT", classSection: "IT C" },
      { name: "VISHALI R", department: "IT", classSection: "IT C" },
      { name: "SUBHALAKSHMI S", department: "EEE", classSection: "EEE" },
      { name: "KAYALVIZHI M", department: "EEE", classSection: "EEE" },
    ],
    "Star Seekers": [
      { name: "ANUSHKA S", department: "AI & ML", classSection: "AIML" },
      { name: "SREENIDHI V", department: "AI & ML", classSection: "AIML" },
      { name: "SINDHUJA SHREE A", department: "AI & ML", classSection: "AIML" },
      { name: "SUBATHRA L", department: "AI & ML", classSection: "AIML" },
      { name: "RUVANTHIKA M E", department: "IT", classSection: "IT C" },
      { name: "SHILPA ESTHER MARY S", department: "IT", classSection: "IT C" },
      { name: "RITHIKA S", department: "IT", classSection: "IT C" },
      { name: "VARSHA R", department: "IT", classSection: "IT C" },
      { name: "SATYA SREE P D", department: "EEE", classSection: "EEE" },
      { name: "INIYA L", department: "EEE", classSection: "EEE" },
    ],
    "Cosmic Crusaders": [
      { name: "NITHYA SREE C", department: "AI & ML", classSection: "AIML" },
      { name: "MASHKURA FATHIMA S", department: "AI & ML", classSection: "AIML" },
      { name: "BHAVANI P", department: "AI & ML", classSection: "AIML" },
      { name: "PRIYADHARSHINI G", department: "AI & ML", classSection: "AIML" },
      { name: "SHRUTHIKA S", department: "IT", classSection: "IT C" },
      { name: "RANJINI S", department: "IT", classSection: "IT C" },
      { name: "TAMIZHARASI N", department: "IT", classSection: "IT C" },
      { name: "DHARSHINI B S", department: "EEE", classSection: "EEE" },
      { name: "CHANDHANAA A", department: "EEE", classSection: "EEE" },
      { name: "KEERTHANA G", department: "EEE", classSection: "EEE" },
    ],
    "Eclipse Elite": [
      { name: "ROOBASRI M", department: "AI & ML", classSection: "AIML" },
      { name: "PONKIRUTHIKA R", department: "AI & ML", classSection: "AIML" },
      { name: "TANUSHRI S R", department: "AI & ML", classSection: "AIML" },
      { name: "VANISHRI S", department: "AI & ML", classSection: "AIML" },
      { name: "VITHIYATHARSINI K", department: "IT", classSection: "IT C" },
      { name: "YASHVI R", department: "IT", classSection: "IT C" },
      { name: "YUVASRI K", department: "IT", classSection: "IT C" },
      { name: "POOJA C", department: "EEE", classSection: "EEE" },
      { name: "SADHANA R K", department: "EEE", classSection: "EEE" },
      { name: "ANURAADHA V", department: "EEE", classSection: "EEE" },
    ],
    "Quasar Questers": [
      { name: "DIVYA DARSHINI A", department: "AI & ML", classSection: "AIML" },
      { name: "SARANYA S", department: "AI & ML", classSection: "AIML" },
      { name: "THANUSIYA VASHANTHA I", department: "IT", classSection: "IT C" },
      { name: "VAITHEESWARI S", department: "IT", classSection: "IT C" },
      { name: "SHRII GOPIKAA K", department: "EEE", classSection: "EEE" },
    ],
    "Meteor Mavericks": [
      { name: "HARIHARAN G", department: "AI & ML", classSection: "AIML" },
      { name: "MAHESWARI P", department: "AI & ML", classSection: "AIML" },
      { name: "RISHI GURUBARAN U", department: "IT", classSection: "IT C" },
      { name: "SIVA PRAKASH P", department: "IT", classSection: "IT C" },
      { name: "LOKESH Y", department: "EEE", classSection: "EEE" },
      { name: "PRABURAM P", department: "EEE", classSection: "EEE" },
    ],
    "Galactic Giants": [
      { name: "NAVEEN KUMAR D", department: "AI & ML", classSection: "AIML" },
      { name: "RAGHUL I", department: "AI & ML", classSection: "AIML" },
      { name: "SRI RAHUL R", department: "AI & ML", classSection: "AIML" },
      { name: "VENKATAKRISHNAN A", department: "IT", classSection: "IT C" },
      { name: "YOGESH C R", department: "IT", classSection: "IT C" },
      { name: "SANJITH S", department: "EEE", classSection: "EEE" },
      { name: "VISHAL M", department: "EEE", classSection: "EEE" },
    ],
  };

  const GROUP4_VERIFIED_MEMBERS = {
    "Phoenix Legion": [
      { name: "Eesa (TL)", department: "ECE", classSection: "ECE" },
      { name: "Dhanush", department: "ECE", classSection: "ECE" },
      { name: "Rahul", department: "CSE", classSection: "CSC" },
      { name: "Sam", department: "CSE", classSection: "CSC" },
      { name: "Praveen", department: "CSE", classSection: "CSC" },
    ],
    "Titan Force": [
      { name: "Maharnitha. K", department: "CSE", classSection: "CSE" },
      { name: "Keerthanaa. R", department: "CSE", classSection: "CSE" },
      { name: "Lakshitha. B", department: "CSE", classSection: "CSE" },
      { name: "Kaviya. D (Team Leader)", department: "CSE", classSection: "CSE" },
      { name: "Mancy Shibi", department: "CSE", classSection: "CSE" },
      { name: "Manya. K", department: "MECH", classSection: "MECH" },
      { name: "Initha. M.A", department: "ECE", classSection: "ECE" },
      { name: "Christina. B", department: "ECE", classSection: "ECE" },
      { name: "Charies. T", department: "ECE", classSection: "ECE" },
      { name: "Akashya. M", department: "ECE", classSection: "ECE" },
    ],
    "Algorithmic Assemblers": [
      { name: "Divya Dharshini. S", department: "MECH", classSection: "Mech" },
      { name: "Vanishree. R", department: "MECH", classSection: "Mech" },
      { name: "Devananda. R", department: "MECH", classSection: "Mech" },
      { name: "Noora. A (Team Leader)", department: "MECH", classSection: "Mech" },
      { name: "Pooja Sri. B", department: "CSE", classSection: "CSE" },
      { name: "P. Roshini", department: "CSE", classSection: "CSE" },
      { name: "Rithikhashri. A", department: "CSE", classSection: "CSE" },
      { name: "Sakthi Sakara. S", department: "CSE", classSection: "CSE" },
      { name: "Nishanthika. G", department: "CSE", classSection: "CSE" },
    ],
    "Nova Squad": [
      { name: "Revin Josh. V.S", department: "MECH", classSection: "Mech" },
      { name: "Sivarama Krishnan. J", department: "MECH", classSection: "Mech" },
      { name: "Rahamathul Ranaman. S.K", department: "MECH", classSection: "Mech" },
      { name: "Linkeshwaran. S", department: "MECH", classSection: "Mech" },
      { name: "Mohith Raj. S", department: "CSE", classSection: "CS" },
      { name: "Rohan. D", department: "CSE", classSection: "CS" },
      { name: "Pranav Aadithya. B", department: "CSE", classSection: "CS" },
      { name: "Arun Grandhi. S (Leader)", department: "ECE", classSection: "ECE" },
      { name: "Mohamed Rehaan. R", department: "ECE", classSection: "ECE" },
      { name: "Jayendra. M", department: "ECE", classSection: "ECE" },
    ],
    "Olympian Order": [
      { name: "Krishnaa. E", department: "ECE", classSection: "ECE" },
      { name: "Pavan. S", department: "CSE", classSection: "CSE" },
      { name: "Rupeshwar. S", department: "CSE", classSection: "CSE" },
      { name: "Praveen. A", department: "CSE", classSection: "CSE" },
      { name: "Ragavan. B.V (Leader)", department: "CSE", classSection: "CSE" },
      { name: "Kavin. S", department: "ECE", classSection: "ECE" },
      { name: "Naveen. K", department: "MECH", classSection: "Mech" },
      { name: "Sanjay. S", department: "MECH", classSection: "Mech" },
      { name: "Siva Prasanth. B", department: "MECH", classSection: "Mech" },
      { name: "Vijaya Kumar. M", department: "MECH", classSection: "Mech" },
    ],
    "Dragon Riders": [
      { name: "Perinbha pranav RJ", department: "CSE", classSection: "CSE B" },
      { name: "Keerthana", department: "CSE", classSection: "CSE B" },
      { name: "Priyadharshini", department: "CSE", classSection: "CSE B" },
      { name: "Lakshita", department: "CSE", classSection: "CSE B" },
      { name: "Kaviya", department: "ECE", classSection: "ECE" },
      { name: "Jeyashree", department: "ECE", classSection: "ECE" },
      { name: "Madhumitha", department: "ECE", classSection: "ECE" },
      { name: "Anushya", department: "ECE", classSection: "ECE" },
      { name: "Fousiya", department: "ECE", classSection: "ECE" },
      { name: "Brindha Lakshmi", department: "ECE", classSection: "ECE" },
    ],
    "Griffin Guild": [
      { name: "Karunya. R", department: "CSE", classSection: "CSE" },
      { name: "Nadhiya. M", department: "CSE", classSection: "CSE" },
      { name: "Poojasri. B", department: "CSE", classSection: "CSE" },
      { name: "Khyati Jain. Y (Team Leader)", department: "CSE", classSection: "CSE" },
      { name: "Keerthana. E", department: "CSE", classSection: "CSE" },
      { name: "Madhivadhani. B", department: "ECE", classSection: "ECE" },
      { name: "Jagapriya Saronjini. J", department: "ECE", classSection: "ECE" },
      { name: "Keerthika S.K", department: "ECE", classSection: "ECE" },
      { name: "Kavipriya. E", department: "ECE", classSection: "ECE" },
      { name: "Deva Dharshini. T", department: "ECE", classSection: "ECE" },
    ],
    "Slayers": [
      { name: "Mandala Ramcharan", department: "ECE", classSection: "ECE" },
      { name: "Kathiravan. R.C", department: "ECE", classSection: "ECE" },
      { name: "Mohamed Kaleemuddin. M.K", department: "ECE", classSection: "ECE" },
      { name: "Roshan Jeffrin R", department: "CSE", classSection: "CSE" },
      { name: "Kishore", department: "ECE", classSection: "ECE" },
      { name: "Mitlesh", department: "CSE", classSection: "CSE" },
      { name: "Jobesh. N.D", department: "MECH", classSection: "Mech" },
      { name: "Dhanush Kumar. R", department: "MECH", classSection: "Mech" },
      { name: "Sarathy. S", department: "MECH", classSection: "Mech" },
    ],
    "Mythic Mavens": [
      { name: "Ajay Sriram", department: "ECE", classSection: "ECE-A" },
      { name: "Aravind", department: "CSE", classSection: "CSE-B" },
      { name: "Dayaa Shankar", department: "MECH", classSection: "Mech" },
      { name: "Faisal", department: "ECE", classSection: "ECE-A" },
      { name: "Lokeshwaran (Captain)", department: "ECE", classSection: "ECE-A" },
      { name: "Hariharan N.R", department: "ECE", classSection: "ECE-A" },
      { name: "Krishnan. E", department: "CSE", classSection: "CSEB" },
      { name: "Niranjan. R", department: "MECH", classSection: "Mech" },
      { name: "Matheshwaran", department: "CSE", classSection: "CSE-B" },
      { name: "Haribam", department: "MECH", classSection: "Mech" },
    ],
    "Titanium": [
      { name: "Eliza winifer", department: "ECE", classSection: "ECE" },
      { name: "Keerthana S", department: "ECE", classSection: "ECE" },
      { name: "Lithikaa", department: "ECE", classSection: "ECE" },
      { name: "Kana kavi T", department: "ECE", classSection: "ECE" },
      { name: "Ainul S", department: "ECE", classSection: "ECE" },
      { name: "Nethra R", department: "CSE", classSection: "CSE" },
      { name: "Kaviya Manivasan", department: "CSE", classSection: "CSE" },
      { name: "Sahithya", department: "CSE", classSection: "CSE" },
      { name: "Kayalvizhi S", department: "CSE", classSection: "CSE" },
      { name: "Rozhini R", department: "CSE", classSection: "CSE" },
    ],
    "Aegis Alliance": [
      { name: "Nehan Mohamed (TL)", department: "MECH", classSection: "ME" },
      { name: "Lakshay Ganesh", department: "MECH", classSection: "ME" },
      { name: "Darvin", department: "CSE", classSection: "CSE-B" },
      { name: "Irfan", department: "CSE", classSection: "CSE-B" },
      { name: "Akash", department: "ECE", classSection: "ECE-A" },
      { name: "Jagan. M", department: "ECE", classSection: "ECE-A" },
      { name: "Gautham", department: "ECE", classSection: "ECE-A" },
      { name: "Mahesh", department: "ECE", classSection: "ECE-A" },
      { name: "Kanthi K.N", department: "ECE", classSection: "ECE-A" },
      { name: "Keswar Moorthi. G", department: "CSE", classSection: "CSE-B" },
    ],
    "Chimera Champions": [
      { name: "T. Guna (Captain)", department: "ECE", classSection: "ECE-A" },
      { name: "Midhun Bharath", department: "ECE", classSection: "ECE-A" },
      { name: "Lokesh", department: "ECE", classSection: "ECE-A" },
      { name: "Clarance", department: "ECE", classSection: "ECE-A" },
      { name: "Mohanraj", department: "CSE", classSection: "CSE-B" },
      { name: "Kiranraj", department: "CSE", classSection: "CSE-B" },
      { name: "Aravindh", department: "MECH", classSection: "Mech" },
      { name: "Bhuvanraj", department: "MECH", classSection: "Mech" },
      { name: "Kavin", department: "CSE", classSection: "CSE-B" },
      { name: "Abhishek", department: "ECE", classSection: "ECE-A" },
    ],
    "Immortal Minds": [
      { name: "Dharshana B", department: "ECE", classSection: "ECE" },
      { name: "Nirosha S", department: "CSE", classSection: "CSE" },
      { name: "Prakalya Devi V", department: "CSE", classSection: "CSE" },
      { name: "Rohitha K", department: "CSE", classSection: "CSE" },
      { name: "Kodhai S", department: "CSE", classSection: "CSE" },
      { name: "Kayalvizhi M", department: "CSE", classSection: "CSE" },
      { name: "Dharshini shree S", department: "ECE", classSection: "ECE" },
      { name: "Kumudhini T", department: "ECE", classSection: "ECE" },
      { name: "Gopika A", department: "ECE", classSection: "ECE" },
      { name: "Johana Pauline S", department: "ECE", classSection: "ECE" },
    ],
  };

  const GROUP5_VERIFIED_MEMBERS = {
    "Voltric Sparks": [
      { name: "S. Santhosh (TL)", department: "Power & Energy", classSection: "Group V" },
      { name: "V.K. Udhaya Narasiman", department: "Power & Energy", classSection: "Group V" },
      { name: "G. Tharunn", department: "Power & Energy", classSection: "Group V" },
      { name: "M. Srivanjith", department: "Power & Energy", classSection: "Group V" },
      { name: "P. Kabilan", department: "Power & Energy", classSection: "Group V" },
      { name: "R. Sethuram", department: "Power & Energy", classSection: "Group V" },
      { name: "S. Thamodharan", department: "Power & Energy", classSection: "Group V" },
      { name: "D. Praneshwaran", department: "Power & Energy", classSection: "Group V" },
      { name: "S. Lakshan Kumar", department: "Power & Energy", classSection: "Group V" },
    ],
    "Wonderwatt": [
      { name: "Vinnarasi. A", department: "Power & Energy", classSection: "Group V" },
      { name: "Sangeetha. M.S", department: "Power & Energy", classSection: "Group V" },
      { name: "Roshini. M", department: "Power & Energy", classSection: "Group V" },
      { name: "Shrinithi Selvaraj", department: "Power & Energy", classSection: "Group V" },
      { name: "Shivani. P", department: "Power & Energy", classSection: "Group V" },
      { name: "Subhasri. S.V", department: "Power & Energy", classSection: "Group V" },
      { name: "Prithikaa. M", department: "Power & Energy", classSection: "Group V" },
      { name: "Krithika. R", department: "Power & Energy", classSection: "Group V" },
      { name: "Naadhira. M", department: "Power & Energy", classSection: "Group V" },
    ],
    "Ignite X": [
      { name: "Keerthika. L (Leader)", department: "IT", classSection: "B.Tech IT" },
      { name: "Mohanagiri Priya. D", department: "IT", classSection: "B.Tech IT" },
      { name: "Pavuluru Yashwini", department: "ECE", classSection: "B.E ECE" },
      { name: "Prashika Sri. CS", department: "IT", classSection: "B.Tech IT" },
      { name: "Sivaranjani. JJ", department: "ECE", classSection: "B.E ECE" },
      { name: "Sharmila. V", department: "ECE", classSection: "B.E ECE" },
      { name: "Shelli Sree. J", department: "ECE", classSection: "B.E ECE" },
      { name: "Subiksha. RS", department: "CSE", classSection: "B.E CSE-C" },
      { name: "Tarunika. M", department: "CSE", classSection: "B.E CSE-C" },
      { name: "Varunavi. S", department: "CSE", classSection: "B.E CSE-C" },
    ],
    "Volt Coders": [
      { name: "P. Pooja (Leader)", department: "IT", classSection: "IT" },
      { name: "T. Sharmila", department: "CSE", classSection: "CSE" },
      { name: "E. Tharani", department: "CSE", classSection: "CSE" },
      { name: "A. Sanjana", department: "CSE", classSection: "CSE" },
      { name: "M. Krishna Ragavi", department: "IT", classSection: "IT" },
      { name: "P. Lokeshwari", department: "IT", classSection: "IT" },
      { name: "V.A. Kamalini", department: "IT", classSection: "IT" },
    ],
    "Watt A Team": [
      { name: "Tanvee. S (Lead)", department: "CSE", classSection: "CSE" },
      { name: "SG Thabanaashree", department: "CSE", classSection: "CSE" },
      { name: "Neha. R Seervi", department: "ECE", classSection: "ECE" },
      { name: "Pavanthi. B", department: "ECE", classSection: "ECE" },
      { name: "Sarumathi A", department: "ECE", classSection: "ECE" },
      { name: "Makishka. S", department: "IT", classSection: "IT" },
      { name: "Keerthi Varshini TR", department: "IT", classSection: "IT" },
      { name: "Tejasri. R", department: "CSE", classSection: "CSE" },
    ],
    "Energon": [
      { name: "Santhosh (Team Leader)", department: "CSE", classSection: "CSE-C" },
      { name: "Shevanesh", department: "CSE", classSection: "CSE-C" },
      { name: "Syed Aamir Suhail", department: "CSE", classSection: "CSE-C" },
      { name: "Syed Rehan Ahmed", department: "CSE", classSection: "CSE-C" },
      { name: "Krisha", department: "IT", classSection: "IT" },
      { name: "Premkumar", department: "IT", classSection: "IT" },
      { name: "Prajan", department: "IT", classSection: "IT" },
      { name: "Vaideshwar", department: "ECE", classSection: "ECE" },
      { name: "Suriya", department: "ECE", classSection: "ECE" },
      { name: "Shanmuganathan", department: "ECE", classSection: "ECE" },
    ],
    "Energy Titans": [
      { name: "Santhosh. R (Tribe Leader)", department: "CSE", classSection: "CSE-C" },
      { name: "Sanjayvasan. T", department: "CSE", classSection: "CSE-C" },
      { name: "Shomnath. G", department: "CSE", classSection: "CSE-C" },
      { name: "Lokeshwaran. K", department: "IT", classSection: "IT-B" },
      { name: "Monesh. S", department: "IT", classSection: "IT-B" },
      { name: "Kishore. S", department: "IT", classSection: "IT-B" },
      { name: "Thiru Kumaran. S", department: "ECE", classSection: "ECE-B" },
      { name: "Mythreyan. S", department: "ECE", classSection: "ECE-B" },
      { name: "Vasan. BK", department: "ECE", classSection: "ECE-B" },
    ],
    "Power Nautical": [
      { name: "A.R. Shreeviha (Team Leader)", department: "CSE", classSection: "CSE" },
      { name: "Sruthilaya. C", department: "ECE", classSection: "ECE" },
      { name: "Pavitha. P", department: "ECE", classSection: "ECE" },
      { name: "Prathi Supriya", department: "ECE", classSection: "ECE" },
      { name: "Shrivarshini", department: "ECE", classSection: "ECE" },
      { name: "Saranya", department: "CSE", classSection: "CS" },
      { name: "Logeshwari. P", department: "IT", classSection: "IT" },
      { name: "Ragavi. S", department: "IT", classSection: "IT" },
      { name: "Tejaswini. G.P", department: "ECE", classSection: "ECE" },
    ],
    "Solar Panel": [
      { name: "M. Rajeshwari (Team Leader)", department: "IT", classSection: "IT" },
      { name: "K. Ragavi", department: "IT", classSection: "IT" },
      { name: "R. Kavi Priya", department: "IT", classSection: "IT" },
      { name: "Navaneetha. S.V", department: "IT", classSection: "IT" },
      { name: "Manasha. S", department: "IT", classSection: "IT" },
      { name: "M. Ragavi", department: "ECE", classSection: "ECE" },
      { name: "Padma Sri. M", department: "ECE", classSection: "ECE" },
      { name: "Syeda Bathul", department: "CSE", classSection: "CSE" },
      { name: "S. Tanushri", department: "CSE", classSection: "CSE" },
    ],
    "Destructive mc²": [
      { name: "Vasanthakumar (Leader)", department: "CSE", classSection: "CSE" },
      { name: "Vasanth", department: "CSE", classSection: "CSE" },
      { name: "Vithesh", department: "CSE", classSection: "CSE" },
      { name: "Tejesh Buddhi", department: "CSE", classSection: "CSE" },
      { name: "Tanveer Ahmad", department: "ECE", classSection: "ECE" },
      { name: "Santhosh", department: "ECE", classSection: "ECE" },
      { name: "Naveen Kumar R", department: "ECE", classSection: "ECE" },
      { name: "Nithish Kumar. K", department: "IT", classSection: "IT" },
      { name: "Kamesh. B.J", department: "IT", classSection: "IT" },
      { name: "John Ajay. A", department: "IT", classSection: "IT" },
    ],
    "Luminous": [
      { name: "Seetha Lakshmi (Group Leader)", department: "CSE", classSection: "CSE" },
      { name: "Swathi. T", department: "CSE", classSection: "CSE" },
      { name: "Varsha. S", department: "CSE", classSection: "CSE" },
      { name: "Priyadharshini. V", department: "IT", classSection: "IT" },
      { name: "Priyanka. K", department: "IT", classSection: "IT" },
      { name: "Priya. A", department: "IT", classSection: "IT" },
      { name: "Joyce Rithanya. P", department: "IT", classSection: "IT" },
    ],
    "Circuit Breakers": [
      { name: "Vijayasri. V (Team Leader)", department: "Power & Energy", classSection: "Group V" },
      { name: "Yashika. E", department: "Power & Energy", classSection: "Group V" },
      { name: "Sanjanya M", department: "Power & Energy", classSection: "Group V" },
      { name: "Shibathul Kai. N", department: "Power & Energy", classSection: "Group V" },
      { name: "Prithika. M", department: "Power & Energy", classSection: "Group V" },
      { name: "Mokshah. S", department: "Power & Energy", classSection: "Group V" },
      { name: "Lakshmi Sowmiya. B", department: "Power & Energy", classSection: "Group V" },
      { name: "R. Vaishnavi", department: "Power & Energy", classSection: "Group V" },
      { name: "Varsha Shree. M", department: "Power & Energy", classSection: "Group V" },
      { name: "Shalini S", department: "Power & Energy", classSection: "Group V" },
    ],
    "Kinetic Knights": [
      { name: "Padmanabhan. M", department: "ECE", classSection: "ECE" },
      { name: "Mohammed Owais. F", department: "ECE", classSection: "ECE" },
      { name: "Vishnu. M", department: "ECE", classSection: "ECE" },
      { name: "Thangappan. E", department: "ECE", classSection: "ECE" },
      { name: "Mohammed Raihan Khan (Lead)", department: "ECE", classSection: "ECE" },
    ],
    "Electra": [
      { name: "P. Sharon Charisma", department: "CSE", classSection: "CSE" },
      { name: "S. Surekha (Team Leader)", department: "CSE", classSection: "CSE" },
      { name: "S.M. Tharini", department: "CSE", classSection: "CSE" },
      { name: "K. Kavya Shree", department: "IT", classSection: "IT" },
      { name: "Karolina Rajkumar", department: "IT", classSection: "IT" },
      { name: "Loshika. P", department: "IT", classSection: "IT" },
      { name: "Roshini. P", department: "ECE", classSection: "ECE" },
      { name: "Tanushree. P", department: "ECE", classSection: "ECE" },
      { name: "Pragathi. B", department: "ECE", classSection: "ECE" },
    ],
    "Volt Warriors": [
      { name: "Sarvagnya PV (Leader)", department: "Power & Energy", classSection: "Group V" },
      { name: "Sathya Narayan M", department: "Power & Energy", classSection: "Group V" },
      { name: "D. Tharun Sayee (Leader/substitute)", department: "Power & Energy", classSection: "Group V" },
      { name: "Santhosh M", department: "Power & Energy", classSection: "Group V" },
      { name: "Vighwash", department: "Power & Energy", classSection: "Group V" },
      { name: "Sathish Kumar G", department: "Power & Energy", classSection: "Group V" },
      { name: "Pon Suresh", department: "Power & Energy", classSection: "Group V" },
      { name: "Pratheep Kumar", department: "Power & Energy", classSection: "Group V" },
    ],
    "Power Dynasty": [
      { name: "Sri Ragaan (Team Leader)", department: "Power & Energy", classSection: "Group V" },
      { name: "M. Mohamed Niyas", department: "IT", classSection: "IT B" },
      { name: "S. Madhavan", department: "IT", classSection: "IT B" },
      { name: "V.K. Varun Srinivas", department: "CSE", classSection: "CSC C" },
      { name: "S. Shashank", department: "CSE", classSection: "CSC C" },
      { name: "M. Kavinesh", department: "IT", classSection: "IT B" },
      { name: "B. Sundar", department: "CSE", classSection: "CSC C" },
      { name: "C. Ramsundar", department: "ECE", classSection: "ECE B" },
      { name: "K.A. Yogesh Kumar", department: "ECE", classSection: "ECE B" },
      { name: "R. Surya", department: "ECE", classSection: "ECE B" },
    ],
    "Power Rangers": [
      { name: "Saravana Selvan. BK (TML)", department: "Power & Energy", classSection: "Group V" },
      { name: "Nidhish Kumar. K", department: "Power & Energy", classSection: "Group V" },
      { name: "Jeshu Gladson. I", department: "Power & Energy", classSection: "Group V" },
      { name: "Mohamed Idris. J", department: "Power & Energy", classSection: "Group V" },
      { name: "Samaran. S", department: "Power & Energy", classSection: "Group V" },
      { name: "Shamsri. K", department: "Power & Energy", classSection: "Group V" },
      { name: "Tarun. S", department: "Power & Energy", classSection: "Group V" },
      { name: "Ramcharan. K.V", department: "Power & Energy", classSection: "Group V" },
      { name: "Naresh Krishna Gnanasekar Vijaya", department: "Power & Energy", classSection: "Group V" },
    ],
    "Enerzinc Pulse": [
      { name: "Thanushri. R (Team Lead)", department: "CSE", classSection: "CSE" },
      { name: "Subraja", department: "CSE", classSection: "CSE" },
      { name: "Yuthikka", department: "CSE", classSection: "CSE" },
      { name: "Vincy Leelavathy", department: "ECE", classSection: "ECE" },
      { name: "Nanthiney. P.V", department: "ECE", classSection: "ECE" },
      { name: "Preetha K", department: "ECE", classSection: "ECE" },
      { name: "Mahalakhshmi", department: "IT", classSection: "IT" },
      { name: "Prathiksha Sri. S", department: "IT", classSection: "IT" },
      { name: "Kavya Sukumar Maheshwaran", department: "IT", classSection: "IT" },
    ],
    "Voltelites": [
      { name: "Thaiyumanavan. M (Team Leader)", department: "CSE", classSection: "CSE" },
      { name: "Sunil. V", department: "CSE", classSection: "CSE" },
      { name: "Taron. C", department: "CSE", classSection: "CSE" },
      { name: "Tharun. B", department: "ECE", classSection: "ECE" },
      { name: "Charshanth. H", department: "CSE", classSection: "CSE" },
      { name: "Mugthilan. P", department: "IT", classSection: "IT" },
      { name: "Kumaran. G", department: "IT", classSection: "IT" },
      { name: "Sobash. S", department: "ECE", classSection: "ECE" },
      { name: "Mohammed Zaarif", department: "ECE", classSection: "ECE" },
      { name: "Nelson. T", department: "IT", classSection: "IT" },
    ],
  };

  const VERIFIED_MAP = {
    ...GROUP1_VERIFIED_MEMBERS,
    ...GROUP2_VERIFIED_MEMBERS,
    ...GROUP3_VERIFIED_MEMBERS,
    ...GROUP4_VERIFIED_MEMBERS,
    ...GROUP5_VERIFIED_MEMBERS,
  };

  // Generate members per tribe (using verified roster where provided)
  const members = [];
  createdTribes.forEach((tribe, tribeIndex) => {
    if (VERIFIED_MAP[tribe.tribeName]) {
      VERIFIED_MAP[tribe.tribeName].forEach((m) => {
        members.push({
          tribeId: tribe._id,
          name: m.name,
          department: m.department,
          classSection: m.classSection,
        });
      });
    } else {
      const venueIndex = Math.floor(tribeIndex / 18);
      const classes = VENUES[venueIndex].participatingClasses;
      for (let i = 0; i < 4; i += 1) {
        const cls = classes[i % classes.length];
        const dept = cls.split("–")[0].trim().split(" ")[0];
        const firstName = FIRST_NAMES[(tribeIndex * 4 + i) % FIRST_NAMES.length];
        const lastName = LAST_NAMES[(tribeIndex * 3 + i * 2) % LAST_NAMES.length];
        members.push({
          tribeId: tribe._id,
          name: `${firstName} ${lastName}`,
          department: dept,
          classSection: cls,
        });
      }
    }
  });
  await Member.insertMany(members);

  // No demo/fake scores: scores start completely clean (0 / unentered)
  // and are updated live in real time as events are judged.

  // Setup initial users/hosts
  const passwordHash = await bcrypt.hash("Admin@123", 10);
  const hosts = venues.map((venue, index) => ({
    name: `${venue.location} Host`,
    email: `host${index + 1}@msec.edu`,
    passwordHash,
    role: "venue_host",
    venueId: venue._id,
    status: "active",
  }));

  await User.insertMany([
    {
      name: "SIP Super Admin",
      email: "admin@msec.edu",
      passwordHash,
      role: "super_admin",
      status: "active",
    },
    {
      name: "SIP Coordinator",
      email: "coordinator@msec.edu",
      passwordHash,
      role: "coordinator",
      venueId: venues[1]._id,
      status: "active",
    },
    ...hosts,
  ]);

  return { seeded: true, tribes: createdTribes.length, venues: venues.length };
}

async function seedIfEmpty() {
  return seedDatabase({ force: false });
}

module.exports = { seedDatabase, seedIfEmpty, VENUES, TRIBE_NAMES, EVENTS };
