const GROUP_MAP = {
  "Group I": {
    groupName: "Group I",
    theme: "Creative & Design",
    motif: "creative",
    classes: ["AI & DS – A", "CSE – A", "Civil"],
    description: "Aesthetics, innovation, visual harmony, drafting and modern architectural concepts.",
    icon: "🎨",
    defaultVenueLocation: "KRS Seminar Hall",
    defaultVenueName: "Venue 1",
  },
  "Group II": {
    groupName: "Group II",
    theme: "Technology & Innovation",
    motif: "technology",
    classes: ["Cyber Security", "AI & DS – B", "IT – A"],
    description: "Next-generation computation, algorithmic intelligence, cyber systems and digital transformation.",
    icon: "💻",
    defaultVenueLocation: "ECE Seminar Hall",
    defaultVenueName: "Venue 2",
  },
  "Group III": {
    groupName: "Group III",
    theme: "Space & Cosmic",
    motif: "space",
    classes: ["AI & ML", "IT – C", "EEE"],
    description: "Galactic exploration, cosmic navigation, stellar engineering and deep-space science.",
    icon: "🚀",
    defaultVenueLocation: "Civil Seminar Hall",
    defaultVenueName: "Venue 3",
  },
  "Group IV": {
    groupName: "Group IV",
    theme: "Legends & Mythology",
    motif: "legends",
    classes: ["ECE – A", "CSE – B", "MECH"],
    description: "Ancient heritage, timeless epics, mythical prowess, and storied folklore reimagined.",
    icon: "🛡️",
    defaultVenueLocation: "MCW Seminar Hall",
    defaultVenueName: "Venue 4",
  },
  "Group V": {
    groupName: "Group V",
    theme: "Power & Energy",
    motif: "power",
    classes: ["ECE – B", "CSE – C", "IT – B"],
    description: "Electrical grid innovation, renewable power, atomic dynamism and sustainable energy.",
    icon: "⚡",
    defaultVenueLocation: "MS Auditorium",
    defaultVenueName: "Venue 5",
  },
};

module.exports = { GROUP_MAP };
